BOARD_TAG    = uno
ARDUINO_PORT = /dev/cu.usb*
ARDUINO_LIBS =
ARDUINO_DIR  = /Applications/Arduino.app/Contents/Resources/Java
ARDMK_DIR    = ~/proj/Arduino-Makefile

include ~/proj/Arduino-Makefile/arduino-mk/Arduino.mk
